version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    command: ["mlflow", "ui", "--host", "0.0.0.0"]
    volumes:
      - ./mlruns:/mlruns
      - ./mlartifacts:/mlartifacts
